name: Build app

on:
  push:
    branches: [ 'master' ]

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build: auto-commit build result from GitHub Actions"
          commit_user: GitHub Actions (Build app)
          commit_email: kusal.kc@student.torrens.edu.au
          commit_options: '--no-verify --signoff'
